# -*- coding: utf-8 -*-
"""distilbert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u7-hijoiHO4hVICsM5m-6rTYMAmtXoPQ
"""

from datasets import load_dataset
from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification
from transformers import Trainer, TrainingArguments
import torch

dataset = load_dataset("imdb")
train_dataset, test_dataset = dataset['train'], dataset['test']

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def preprocess_function(example):
  return tokenizer(example['text'],truncation=True,padding=True,max_length=512)

tokenized_train = train_dataset.map(preprocess_function, batched=True)
tokenized_test = test_dataset.map(preprocess_function, batched=True)

model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased",num_labels=2)

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir='./logs',
    logging_steps=10,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
)

trainer.train()

result = trainer.evaluate()
print(f"Evaluation Results:{result}")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

new_review = "This movie was fantastic! I loved every minute of it"
inputs = tokenizer(new_review, return_tensors="pt", truncation=True, padding=True, max_length=512)
inputs = {key: value.to(device) for key, value in inputs.items()}

outputs = model(**inputs)
predictions = torch.argmax(outputs.logits, dim=-1)
print("Positive" if predictions.item() == 1 else "Negative")