# -*- coding: utf-8 -*-
"""BiLSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHrTDKoIopaT9QnrtYJGP04EyudVkLMb
"""

import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
import matplotlib.pyplot as plt

dataset = tfds.load('imdb_reviews', as_supervised=True)
train_dataset, test_dataset = dataset['train'], dataset['test']

batch_size = 32

train_dataset = train_dataset.shuffle(10000).batch(batch_size)
test_dataset = test_dataset.batch(batch_size)

example,label = next(iter(train_dataset))
print("Text:\n",example.numpy()[0])
print("\nLabel:",label.numpy()[0])

vectorize_layer = tf.keras.layers.TextVectorization(output_mode='int',output_sequence_length=100)
vectorize_layer.adapt(train_dataset.map(lambda x,y :x))

model = tf.keras.Sequential([
    vectorize_layer,
    tf.keras.layers.Embedding(
        len(vectorize_layer.get_vocabulary()), 64, mask_zero = True),
    tf.keras.layers.Bidirectional(
        tf.keras.layers.LSTM(64,return_sequences=True)),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(32)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1)
])

model.build(input_shape=(None,))


model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(),
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    train_dataset,
    epochs = 3,
    validation_data = test_dataset,
)

review = tf.constant(["This movie was amazing and engaging"])
prob = tf.sigmoid(model.predict(review))[0][0]

sentiment = "Positive" if prob >= 0.5 else "Negative"
print(f"Sentiment:{sentiment},Probability:{prob:.2f}")