# -*- coding: utf-8 -*-
"""elmo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UCN0epBxf3McaK_IOoRRaeo_YWsXWZHP
"""

import tensorflow as tf
import tensorflow_hub as hub

elmo = hub.load("https://tfhub.dev/google/elmo/3")

def get_elmo_embedding(sentence):
  embeddings = elmo.signatures["default"](tf.constant(sentence))["elmo"]
  return embeddings

sentences = [
    "The bank will approve your loan.",
    "He sat by the bank of the river."
]
embeddings = get_elmo_embedding(sentences)
print(embeddings)