# -*- coding: utf-8 -*-
"""roberta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BaAsfVTTIhO66-KR2unhaKUFB6Pukf3i
"""

from transformers import pipeline

classifier = pipeline("sentiment-analysis",model="roberta-base")

result = classifier("The movie was absolutely fantastic!")

print(result)